blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    #post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    #path('',views.PostListView.as_view(),name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    #share post via email
    path('<int:post_id>/share/',views.post_share,name='post_share'),
    path('<int:post_id>/comment/',views.post_comment, name='post_comment')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


# Create a custom object manager
class PublishedManager(models.Manager):
    """Custom objects manager for published Posts"""
    
    def get_queryset(self):
        return super().get_queryset().filter(status= Post.Status.PUBLISHED)



class Post(models.Model):
    """Stores the data for posts."""
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'


    #Fields 
    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250,
        # Make the slug unique for the publication date.
        unique_for_date='publish'
    )
    #tags field
    tags = TaggableManager()
    #author field
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='blog_posts'
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add= True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices= Status,
        default=Status.DRAFT
    )

    #Agregando el custom object manager
    objects = models.Manager()#default manager
    published = PublishedManager()

    class Meta:
        """Adding some aditional settings to the model."""
        # Defining the field and order to be presented the data
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]
        

    def get_absolute_url(self):
        """Returning the cannonical url for a specific post."""
        return reverse(
            'blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )


    def __str__(self):
        """Return a string represantantion of the Post"""
        return self.title
    

class Comment(models.Model):
    """Defines the structure for comments."""
    
    post = models.ForeignKey(
        Post, 
        on_delete= models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now= True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]


    def __str__(self):
        return f"Comment by {self.name} on {self.created}"

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    """Create the form to share posts via email."""
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget= forms.Textarea
    )


class CommentForm(forms.ModelForm):
    """Create the html form for Comment model."""
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.views.decorators.http import require_POST
from django.db.models import Count
from taggit.models import Tag
from .models import Post
from .forms import EmailPostForm, CommentForm


def post_list(request, tag_slug=None):
    """Retrieves the list of published posts."""

    posts_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(
            Tag,
            slug= tag_slug
        )
        posts_list = posts_list.filter(tags__in = [tag])
    paginator = Paginator(posts_list,3)# pagination with 3 post per page
    page_number = request.GET.get('page', 1)
    
    try:
       
        posts = paginator.page(page_number)

    except EmptyPage:
        #if the number is out of range show the las page
        # paginator.num_pages = last page
        posts = paginator.page(paginator.num_pages)
    
    # in the case page parameter is not an integer example  example.com/?page=asdf
    except PageNotAnInteger:
        posts = paginator.page(1)


    return render(
        request, 
        'blog/post/list.html',
        {
            'posts':posts,
            'tag':tag
         }
    )


def post_detail(request, year, month, day, post):
    """Retrieves the details of a specific Post."""
    post = get_object_or_404(
        Post,
        status= Post.Status.PUBLISHED,
        slug= post,
        publish__year = year,
        publish__month= month,
        publish__day = day
        
    )
    #getting all comments with active = true
    comments = post.comments.filter(active=True)
    #form for users to comment
    form = CommentForm()
    
    #retrieving posts related by tags

    post_tags_ids = post.tags.values_list('id', flat=True)# getting all the ids of each tag associated to the post
    similar_posts = Post.objects.filter(
        tags__in = post_tags_ids
    ).exclude(id=post.id) # get all the posts that have the same tags of the current post

    similar_posts = similar_posts.annotate(
        same_tags = Count('tags')
    ).order_by('-same_tags','-publish')[:4]

    return render(
        request,
        'blog/post/detail.html',
        {
            'post':post,
            'comments':comments,
            'form':form,
            'similar_posts': similar_posts
         }
    )

#Class-based views
class PostListView(ListView):
    """Class-based List-view of posts."""
    queryset = Post.published.all()
    paginate_by = 3
    context_object_name = 'posts'
    template_name = 'blog/post/list.html'


def post_share(request, post_id):
    """Allows post sharing via email."""
    post = get_object_or_404(
        Post,
        id=post_id,
        status= Post.Status.PUBLISHED
    )
    sent = False

    if request.method == 'POST':
        # form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data #parameters validated
            name = cleaned_data['name']
            email = cleaned_data['email']
            comments = cleaned_data['comments']
            recipients = [cleaned_data['to']]# this field must be a tuple or a list

            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = (f"{name} {email} "
                       f"recomends you read, {post.title}")
            message = (f"Read {post.title} at {post_url}\n\n"
                f"{name}'s comments: {comments}")
            
            send_mail(subject, message,from_email=None,recipient_list=recipients)
            sent = True
    else:
        form = EmailPostForm()

    return render(
        request,
        'blog/post/share.html',
        {
            'post': post,
            'form':form,
            'sent':sent
        }
    )


@require_POST #This decorator forces the view to use only POST method
def post_comment(request, post_id):
    """Add a new comment to a specific post."""
    post = get_object_or_404(
        Post,
        id=post_id,
        status= Post.Status.PUBLISHED
    )
    comment = None
    # a comment was posted
    form = CommentForm(data= request.POST)
    if form.is_valid():
        comment = form.save(commit=False) # create an instance of the Model without saving it
        comment.post = post #assign the post to the comment
        comment.save() # save the comment to the database
    
    return render(
        request,
        'blog/post/comment.html',
        {
            'post': post,
            'form': form,
            'comment': comment
        }
    )

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/blog.css"%}">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My Blog</h2>
        <p>This is my blog</p>

    </div>
</body>
</html>

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links"> 
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">Previous</a>        
        {%endif%}
        <span class="current">
            Page {{page.number}} of {{page.paginator.num_pages}}.
        </span>
        {% if page.has_next %}
        <a href="?page={{page.next_page_number}}">Next</a>
        {%endif%}
    </span>

</div>

blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}
{%block title%} Add Comment {%endblock%}
{%block content%}
    {%if comment%}
        <p>your comment has been added.</p>
        <div>
            <a href="{{post.get_absolute_url}}">Back to post</a>
        </div>
    {%else%}
        {%include 'blog/post/includes/comment_form.html'%}    
    
    {%endif%}
    

{%endblock%}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %} {{post.title}} {% endblock %}
{% block content%}
    <h1>{{post.title}}</h1>
    <p>
        Published {{post.publish}} by {{post.author}}
    </p>
    {{post.body|linebreaks}}
    <div>
        <a href="{%url 'blog:post_share' post.id%}">Share this post</a>
    </div>
    <h2>Similar Posts:</h2>
    {%for post in similar_posts%}
    <div class="similar_posts">
        <p>
            <a href="{{ post.get_absolute_url}}">{{post.title}}</a>
        </p>
    {%empty%}
        <p>
            <stron>
                There are no similar posts.
            </stron>
        </p>
    {%endfor%}

    {% with comments.count as total_comments %}

        <h2>{{total_comments}} comment{{total_comments|pluralize}}</h2>

    {%endwith%}
    {%for comment in comments%}
        <div>
            <p>
                Comment {{forloop.counter}} by {{comment.name}}
                {{comment.created}}
            </p>
            {{comment.body|linebreaks}}
        </div>
        {%empty%}
        <p>There are no comments.</p>
    {%endfor%}
    {% include "blog/post/includes/comment_form.html"%}
{%endblock%}

blog/templates/blog/post/includes/comment_form.html
<h2>Add new comment</h2>
<form method="post" action="{% url 'blog:post_comment' post.id%}">
    {%csrf_token%}
    <div class="left">
        {{form.name.as_field_group}}
    </div>
    <div class="left">
        {{form.email.as_field_group}}
    </div>
    {{form.body.as_field_group}}
    <p>
        <input type="submit" value="Add comment">
    </p>

</form>

blog/templates/blog/post/list.html
{% extends "blog/base.html"%}
{% block title %}My Blog {% endblock %}
{% block content%}
<h1>My Blog</h1>
{%if tag%}
    <h2>Post tagged with: "{{tag.name}}"</h2>
{%endif%}
{% for post in posts %}
    <h2>
        <a href="{{ post.get_absolute_url }}">
            {{post.title}}
        </a>
    </h2>
    <p>
        Tags:
        {%for tag in post.tags.all%}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag.name}}</a>
           
            {% if not for_loop.last%}
                ,
            {%endif%}
        {%endfor%}
    </p>
    <p>
        Published {{post.publish}}  by {{post.author}}
    </p>
    {{post.body|truncatewords:30|linebreaks}}
{% endfor %}
{% include "blog/pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %} Share a Post {%endblock%}
{%block content%}
    {% if sent%}
        <h2>Email successfully sent</h2>
        <p>
            "{{post.title}}" was successfully sent to {{form.cleanned_data.to}}

        </p>
    {%else%}
        <h2>Share "{{post.title}}" via email</h2>    
        <form method="post">
            {%csrf_token%}
            {{form.as_div}}
            <input type="submit" value="Send e-mail">
        </form>
    {%endif%}
{%endblock%}